<a href="https://colab.research.google.com/github/19PA1A0496/10-03-2020/blob/master/ques_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a 2-D NumPy array of size (4,5) and perform following operations on it

a. Modify elements less than 4 with -1 in the array

b. Apply “sin” operation on every element in the array and multiple by 10.

c. Print 2nd column from 2nd and 3rd row

d. Print element from last row and last column using negative indexing.

e. Transpose a matrix

f. Reshape the array into 2 rows and 10 columns

g. Print last row using negative indexing

h. Convert a 2-D array into 1-D array. Flatten the array

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,2,3,4,5],[2,4,6,7,8],[3,5,8,0,1],[11,4,7,5,1]])
x

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  7,  8],
       [ 3,  5,  8,  0,  1],
       [11,  4,  7,  5,  1]])

In [ ]:
x.shape

(4, 5)

In [ ]:
n = x
n[n<4] = -1 #replacing numbers less than 4 with -1
n

array([[-1, -1, -1,  4,  5],
       [-1,  4,  6,  7,  8],
       [-1,  5,  8, -1, -1],
       [11,  4,  7,  5, -1]])

In [ ]:
10*np.sin(x) #applying sin and multipling elements with 10

array([[-8.41470985, -8.41470985, -8.41470985, -7.56802495, -9.58924275],
       [-8.41470985, -7.56802495, -2.79415498,  6.56986599,  9.89358247],
       [-8.41470985, -9.58924275,  9.89358247, -8.41470985, -8.41470985],
       [-9.99990207, -7.56802495,  6.56986599, -9.58924275, -8.41470985]])

In [ ]:
x[1:3,1:2] #2nd and 3rd elements in 2nd column

array([[4],
       [5]])

In [ ]:
x[-1,-1] # element at last row and last column

1

In [ ]:
x.T #transpose of matrix

array([[ 1,  2,  3, 11],
       [ 2,  4,  5,  4],
       [ 3,  6,  8,  7],
       [ 4,  7,  0,  5],
       [ 5,  8,  1,  1]])

In [ ]:
x.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  2,  4,  6,  7,  8],
       [ 3,  5,  8,  0,  1, 11,  4,  7,  5,  1]])

In [ ]:
x[-1] #last row of matrix

array([11,  4,  7,  5,  1])

In [ ]:
x.ravel()

array([ 1,  2,  3,  4,  5,  2,  4,  6,  7,  8,  3,  5,  8,  0,  1, 11,  4,
        7,  5,  1])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  2,  4,  6,  7,  8,  3,  5,  8,  0,  1, 11,  4,
        7,  5,  1])